// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oftjfsscyjutechgzzfi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9mdGpmc3NjeWp1dGVjaGd6emZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2Mzc4ODEsImV4cCI6MjA3MTIxMzg4MX0.RcbjfgqUQ7SzYFRhgaVUycAtibGH7RkWY43Tr_jFuYE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});